from tkinter import *

raiz=Tk()
raiz.title("ventana de pruebas")
#raiz.resizable(True,False)
#raiz.iconbitmap("")
#raiz.geometry("650x350")
raiz.config(bg="orange")
raiz.config(bd="45")
raiz.config(relief="groove")
raiz.config(cursor="hand2")
miframe=Frame()
miframe.pack()
miframe.config(bg="grey")
miframe.config(width="650",height="350")
miframe.config(bd="35")
miframe.config(relief="sunken")
miframe.config(cursor="pirate")
raiz.mainloop()